- type: web
  name: task-prioritization-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: GOOGLE_API_KEY
      sync: false
    - key: PYTHON_VERSION
      value: 3.12.x # Or the latest stable version you want to use.
